# Generated by Django 4.1.1 on 2022-10-04 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 10, 10, 2, 890895)),
        ),
    ]
