# Generated by Django 4.1.1 on 2022-11-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('num_man', models.IntegerField()),
                ('num_women', models.IntegerField()),
            ],
            options={
                'db_table': 'numcar',
            },
        ),
        migrations.CreateModel(
            name='NumEvCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('num_evcar', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
            options={
                'db_table': 'numevcar',
            },
        ),
        migrations.CreateModel(
            name='NumEvCar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region2', models.CharField(max_length=20)),
                ('num_evcar2', models.IntegerField()),
                ('percent2', models.IntegerField()),
            ],
            options={
                'db_table': 'numevcar2',
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=20)),
                ('two', models.IntegerField()),
            ],
            options={
                'db_table': 'test1',
            },
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=20)),
                ('two', models.IntegerField()),
            ],
            options={
                'db_table': 'test2',
            },
        ),
    ]
