# Generated by Django 4.1.1 on 2022-10-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=20)),
                ('attached_file', models.FileField(null=True, upload_to='%Y-%m-%d/')),
            ],
        ),
    ]
