# Generated by Django 4.1.1 on 2022-10-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='original_file_name',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
