# Generated by Django 4.1.1 on 2022-09-28 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 20, 25, 179281)),
        ),
        migrations.AlterField(
            model_name='board',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
